"""add unique constraint on dynastyrun team

Revision ID: 7074777b8245
Revises: ed6e57db6c32
Create Date: 2026-08-16 09:37:37.918746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7074777b8245'
down_revision = 'ed6e57db6c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Named explicitly: autogenerate emitted `None` for both the create and
    # the drop, which lets Postgres pick the name on create but then can't
    # target it by name on downgrade — that would fail. Naming it here
    # keeps upgrade/downgrade symmetric.
    op.create_unique_constraint("uq_dynastyrun_team", "dynastyrun", ["team"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_dynastyrun_team", "dynastyrun", type_="unique")
    # ### end Alembic commands ###
