"""snapcount core schema

Revision ID: ed6e57db6c32
Revises: fe56fa70289e
Create Date: 2026-08-16 09:03:16.931769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed6e57db6c32'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('week_count', sa.Integer(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('team',
    sa.Column('abbr', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('abbr')
    )
    op.create_table('champion',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['team'], ['team.abbr'], ),
    sa.PrimaryKeyConstraint('season')
    )
    op.create_table('dynastyrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titles', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['team'], ['team.abbr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('spread_line', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('overtime', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['team.abbr'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.abbr'], ),
    sa.ForeignKeyConstraint(['season'], ['season.year'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_season_week', 'game', ['season', 'week'], unique=False)
    op.create_table('player',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team'], ['team.abbr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamseasonstat',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Integer(), nullable=False),
    sa.Column('points_against', sa.Integer(), nullable=False),
    sa.Column('sos', sa.Float(), nullable=False),
    sa.Column('streak', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('playoff_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season'], ['season.year'], ),
    sa.ForeignKeyConstraint(['team'], ['team.abbr'], ),
    sa.PrimaryKeyConstraint('season', 'team')
    )
    op.create_table('playerseasonstat',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('seasons_played', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('carries', sa.Integer(), nullable=False),
    sa.Column('targets', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.Column('passing_yards', sa.Integer(), nullable=False),
    sa.Column('passing_tds', sa.Integer(), nullable=False),
    sa.Column('passing_epa', sa.Float(), nullable=False),
    sa.Column('rushing_yards', sa.Integer(), nullable=False),
    sa.Column('rushing_tds', sa.Integer(), nullable=False),
    sa.Column('rushing_epa', sa.Float(), nullable=False),
    sa.Column('receiving_yards', sa.Integer(), nullable=False),
    sa.Column('receiving_tds', sa.Integer(), nullable=False),
    sa.Column('receiving_epa', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.year'], ),
    sa.ForeignKeyConstraint(['team'], ['team.abbr'], ),
    sa.PrimaryKeyConstraint('season', 'player_id')
    )
    op.create_index('ix_playerseasonstat_season_position', 'playerseasonstat', ['season', 'position'], unique=False)
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_index('ix_playerseasonstat_season_position', table_name='playerseasonstat')
    op.drop_table('playerseasonstat')
    op.drop_table('teamseasonstat')
    op.drop_table('player')
    op.drop_index('ix_game_season_week', table_name='game')
    op.drop_table('game')
    op.drop_table('dynastyrun')
    op.drop_table('champion')
    op.drop_table('team')
    op.drop_table('season')
    op.drop_table('ingestrun')
    # ### end Alembic commands ###
