"""A committed slice of the real 2016-2025 backfill, for databases that
don't have one.

The API route tests assert against real ingested data — DET's 15-2 2024,
the sixteen games in week 15, a ten-season quarterback, New England's six
titles. That data reaches the dev database through `app.ingest.runner`,
which pulls from nflverse over the network across a decade of seasons: far
too slow and too external to run in CI, where every job starts from
`docker compose down -v` and an empty volume.

So CI got no data at all, and 51 tests failed there while 147 passed
locally — the suite was reading state it never established. This package
closes that gap: `load_backfill` imports a fixed slice of the same real
rows, so the assertions hold identically in both places without being
rewritten against invented numbers.

`backfill.json.gz` is generated by `tests.fixtures.generate` (see its
docstring for what the slice contains and why). It is loaded through
`model_validate`, not `Model(**row)` — SQLModel skips validation in
`__init__` for `table=True` models, which would let an ISO-8601 string
reach a `DateTime` column unparsed.
"""

import gzip
import json
from pathlib import Path
from typing import Any

from sqlmodel import Session, SQLModel

from app.models import Game, Player, PlayerSeasonStat, Season, TeamSeasonStat

FIXTURE_PATH = Path(__file__).with_name("backfill.json.gz")

# Keyed by the name `generate` writes, and iterated in this order so each
# table's foreign keys resolve against tables already inserted. `Team` is
# absent by design — `seed_teams` produces it — but every table here
# references it, so the caller must seed teams first.
_MODELS: dict[str, type[SQLModel]] = {
    "Season": Season,
    "Game": Game,
    "TeamSeasonStat": TeamSeasonStat,
    "Player": Player,
    "PlayerSeasonStat": PlayerSeasonStat,
}


def load_backfill(session: Session) -> dict[str, int]:
    """Insert the fixture slice into `session` and return the row count per
    table. Does not commit — the caller owns the transaction boundary.

    Assumes the target tables are empty; it inserts rather than upserts, so
    a collision surfaces as an IntegrityError instead of being papered over.
    """
    with gzip.open(FIXTURE_PATH, "rt") as raw:
        payload: dict[str, Any] = json.load(raw)

    tables: dict[str, list[dict[str, Any]]] = payload["tables"]
    unknown = set(tables) - set(_MODELS)
    if unknown:
        raise ValueError(
            f"{FIXTURE_PATH.name} carries tables this loader does not know "
            f"({sorted(unknown)}) — regenerate it with tests.fixtures.generate."
        )

    counts = {}
    for name, model in _MODELS.items():
        rows = tables.get(name, [])
        session.add_all([model.model_validate(row) for row in rows])
        # Flushed per table so a foreign key that the next table depends on
        # is already in the database, and so a failure names the table it
        # came from rather than surfacing at the end of a 4,000-row batch.
        session.flush()
        counts[name] = len(rows)
    return counts
